//This c++ code is generated by PictoBlox

void setup() 
{
	//put your setup code here, to run once:
	pinMode(13, OUTPUT);
	pinMode(9, INPUT);
	digitalWrite(13, true);
	Serial.begin(9600);
}

void loop()
 {
	//put your main code here, to run repeatedly:
	
		digitalWrite(13, true);
    Serial.println(digitalRead(9));
	if((digitalRead(9) ==0 ))
   {
		digitalWrite(13, false);
	}
}

